### ISSUE TITLE
AttributeError: Invalid configuration for faker locale `en_US`

### ISSUE THREAD

**Issue by ANBAL534** [FallenAngel-PP/PP_Stuff_Tool_for_Linux#2]
```Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1921, in __call__
  File "pp_stuff_tool.py", line 4513, in rename_for_OS
  File "pp_stuff_tool.py", line 351, in signing_keys_func
  File "pp_stuff_tool.py", line 276, in generate_key_and_certificate
  File "faker/factory.py", line 45, in create
AttributeError: Invalid configuration for faker locale `en_US`
```

When clicking on Renaming method button

**Comment by FallenAngel-PP** [comment]
Fixed it by removing Faker and using another method
